# Module 09 -- Figure 6: evidence-driven systems synthesis model.
#
# This script performs NO new statistical testing. Every node, edge, direction, and
# replication-status label is read or re-derived (via the SAME method already used and
# committed in its source module -- e.g. cutree() at the same r>0.7 cutoff already
# documented in 06_regulation_communication/03c_h4_module_clustering.R) directly from
# already-committed results/*.csv and results/*.rds files. Nothing here is hand-typed from
# memory of the README text, specifically to avoid transcription drift between this figure
# and the modules it summarizes.
#
# Encoding (fixed, matches the design confirmed 2026-08-02):
#   - Node fill:      responder-elevated (blue) / non_responder-elevated (vermillion) /
#                     neutral (compartments -- attribution layer, not itself directional)
#   - Node border:    solid = Moderate-or-above evidence generated within this project;
#                     dashed = literature-derived, external, not generated by this project
#   - Edge line type: solid = a finding generated within this project (H1/H2/H4 primary);
#                     dashed = a literature-derived or externally-unvalidated link
#   - Node subtitle:  factual H5 replication tag, computed from h5a/h5b's own committed
#                     concordant_direction/significant columns, never asserted from memory

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
})

source("R/theme_project.R")

# ---- 1. H1: ligand direction (from H1's own committed ranked table) ------------------------

h1 <- read.csv("results/h1_discovery_screen_ranked.csv", stringsAsFactors = FALSE)
ligand_genes <- c("LTB", "CCL3", "CCL4", "CXCL13")
h1_hits <- h1[h1$gene %in% ligand_genes, c("gene", "logFC", "adj.P.Val")]
stopifnot("Expected exactly the 4 H1 FDR<0.05 ligand hits" = nrow(h1_hits) == 4)
h1_hits$group <- ifelse(h1_hits$logFC < 0, "responder", "non_responder")

# ---- 2. H2: compartment attribution for the same 4 genes (from H2's own committed table) ---

h2 <- read.csv("results/h2_compartment_specificity.csv", stringsAsFactors = FALSE)
h2_hits <- h2[h2$gene %in% ligand_genes, c("gene", "dominant_compartment")]
stopifnot("Expected a dominant-compartment call for all 4 H1 ligand hits" = nrow(h2_hits) == 4)

# ---- 3. H4: TF-module identity, re-derived at the SAME r>0.7 cutoff already committed -------
# (03c_h4_module_clustering.R already saved cor_mat/hc; cutree() at h = 1-0.7 reproduces
# exactly the "13 modules at r>0.7" already reported -- not a new analysis, the same cut.)

h4_clust <- readRDS("results/h4_tf_module_clustering.rds")
clusters <- cutree(h4_clust$hc, h = 1 - 0.7)
sig05 <- h4_clust$sig05

module_of <- function(tf) unname(clusters[tf])
module_members <- function(cl) names(clusters)[clusters == cl]
module_direction <- function(cl) {
  members <- module_members(cl)
  dirs <- sign(sig05$logFC[match(members, sig05$TF)])
  if (length(unique(dirs)) != 1) stop("Mixed-direction module encountered unexpectedly")
  if (dirs[1] > 0) "non_responder" else "responder"
}

cl_metabolic  <- module_of("SREBF1")   # metabolic/nuclear-receptor module
cl_e2f        <- module_of("E2F1")     # E2F proliferation module
cl_lymphocyte <- module_of("IKZF3")    # lymphocyte-differentiation module
stopifnot(
  "SREBF1/E2F1/IKZF3 expected in three DIFFERENT modules at r>0.7" =
    length(unique(c(cl_metabolic, cl_e2f, cl_lymphocyte))) == 3
)

h4_modules <- data.frame(
  module_label = c(
    paste0("Metabolic/NR module\n(", length(module_members(cl_metabolic)), " TFs incl. SREBF1)"),
    paste0("E2F proliferation module\n(", length(module_members(cl_e2f)), " TFs incl. E2F1)"),
    paste0("Lymphocyte-diff. module\n(", length(module_members(cl_lymphocyte)), " TFs incl. IKZF3)")
  ),
  cluster_id = c(cl_metabolic, cl_e2f, cl_lymphocyte),
  group = c(module_direction(cl_metabolic), module_direction(cl_e2f), module_direction(cl_lymphocyte)),
  h5b_module = c("Module1", "Module2", NA),  # H5b's own pre-registered module names; NA = not tested
  stringsAsFactors = FALSE
)

# ---- 4. H5a/H5b: replication tag, computed from the committed cohort-level verdicts ---------
# Standing rule (pre-registered, applied without exception): replication requires BOTH
# concordant direction AND significance in an external cohort; neither alone is sufficient.

h5a <- read.csv("results/h5a_gene_replication_combined.csv", stringsAsFactors = FALSE)
h5b <- read.csv("results/h5b_tf_module_replication_combined.csv", stringsAsFactors = FALSE)

replication_tag <- function(rows) {
  # rows: one row per external cohort for a single gene/module, with concordant_direction
  # and significant columns (exact columns already committed by 04_h5a.../06_h5b...R)
  any_reversed <- any(!rows$concordant_direction)
  any_sig_concordant <- any(rows$concordant_direction & rows$significant)
  if (any_sig_concordant) "H5: Replicated"
  else if (any_reversed) "H5a/b: Negative finding"
  else "H5a/b: Exploratory (concordant, ns)"
}

h5a_tags <- sapply(ligand_genes, function(g) replication_tag(h5a[h5a$gene == g, ]))
h5b_tags <- sapply(c("Module1", "Module2"), function(m) replication_tag(h5b[h5b$module == m, ]))

# ---- 5. H5c: literature-overlap genes (from H5c's own committed table, not re-typed) --------

h5c <- read.csv("results/h5c_literature_concordance.csv", stringsAsFactors = FALSE)
wang_hit_genes <- trimws(strsplit(
  h5c$overlap_genes[h5c$population == "H1_FDR05_hits" & h5c$marker_set == "Wang2025"], ";"
)[[1]])
stopifnot("Expected CCL3 as the Wang2025 overlap gene among H1's FDR<0.05 hits" =
  identical(wang_hit_genes, "CCL3"))

# ---- 6. Literature-derived interpretive statements (quoted directly from the ledger, ---------
#         not retyped from memory of the README prose) ---------------------------------------

ledger <- read.delim("results/evidence_ledger.tsv", sep = "\t", stringsAsFactors = FALSE)
h1_interp <- ledger$interpretation[ledger$hypothesis == "H1"]
h4_interp <- ledger$interpretation[ledger$hypothesis == "H4"]
stopifnot(grepl("lymphotoxin", h1_interp, ignore.case = TRUE))
stopifnot(grepl("exhaustion", h4_interp, ignore.case = TRUE))

# ---- 7. Node coordinates (manual layout -- ggplot2 only, matching this project's existing --
#         hand-built-schematic convention for decision-tree/audit-table panels; no new
#         layout-algorithm dependency introduced) --------------------------------------------

# Layout: four aligned rows (compartment -- ligand), each 2.2 units apart (ample margin for
# 3-line boxes at most 0.5 half-height); a separate module band well below, same spacing;
# outcome nodes to the right, y set to the mean position of the nodes feeding each one;
# literature nodes placed directly above/below their single source node (short, uncrossed
# vertical edges) or to the right of their source at a y clear of the outcome column.

row_y <- c(LTB = 8.8, CXCL13 = 6.6, CCL3 = 4.4, CCL4 = 2.2)
mod_y <- c(lymphocyte = -0.2, metabolic = -2.4, e2f = -4.6)

compartments <- data.frame(
  id = c("B_cell", "T_cell", "Myeloid", "NK"),
  x = 0, y = unname(row_y[c("LTB", "CXCL13", "CCL3", "CCL4")]),
  label = c("B cell", "T cell", "Myeloid", "NK"),
  group = "neutral", border = "solid", tier = "compartment"
)

ligands <- h1_hits %>%
  left_join(h2_hits, by = "gene") %>%
  mutate(
    x = 2.4,
    y = unname(row_y[gene]),
    label = paste0(gene, "\n(H1, FDR=", signif(adj.P.Val, 2), ")"),
    border = "solid", tier = "ligand", id = gene
  )

modules <- h4_modules %>%
  mutate(
    x = 2.4,
    y = c(unname(mod_y["metabolic"]), unname(mod_y["e2f"]), unname(mod_y["lymphocyte"])),
    label = module_label, border = "solid", tier = "module", id = module_label
  )

responder_y    <- mean(c(row_y["LTB"], mod_y["lymphocyte"]))
nonresponder_y <- mean(c(row_y["CXCL13"], row_y["CCL3"], row_y["CCL4"], mod_y["metabolic"], mod_y["e2f"]))

outcomes <- data.frame(
  id = c("Responder", "Non_responder"),
  x = 4.8, y = c(responder_y, nonresponder_y),
  label = c("Responder", "Non-responder"),
  group = c("responder", "non_responder"), border = "solid", tier = "outcome"
)

lit_nodes <- data.frame(
  id = c("lit_TLS", "lit_exhaustion", "lit_wang"),
  x = c(2.4, 2.4, 4.8),
  # lit_exhaustion placed BELOW the lowest module (e2f), with a wide margin -- its edge
  # (below) is deliberately curved so it doesn't pass straight down through the
  # Metabolic/NR or E2F module boxes sitting in between
  y = c(row_y["LTB"] + 2.2, mod_y["e2f"] - 2.4, mod_y["metabolic"] - 0.4),
  label = c(
    "Published TLS/lymphotoxin\nbiology (literature only)",
    "Published T-cell-exhaustion-\nrestraint biology (lit. only)",
    paste0("Wang 2025 TAN atlas (H5c)\noverlap: ", paste(wang_hit_genes, collapse = ", "))
  ),
  group = "neutral", border = "dashed", tier = "literature"
)

nodes <- bind_rows(
  compartments[, c("id", "x", "y", "label", "group", "border", "tier")],
  ligands[, c("id", "x", "y", "label", "group", "border", "tier")],
  modules[, c("id", "x", "y", "label", "group", "border", "tier")],
  outcomes[, c("id", "x", "y", "label", "group", "border", "tier")],
  lit_nodes[, c("id", "x", "y", "label", "group", "border", "tier")]
)

# ---- 8. Edges (every edge traceable to a specific, already-completed module) ----------------

edge_row <- function(from_id, to_id, linetype, curvature = 0, note = "") {
  f <- nodes[nodes$id == from_id, c("x", "y")]
  t <- nodes[nodes$id == to_id, c("x", "y")]
  data.frame(x = f$x, y = f$y, xend = t$x, yend = t$y, linetype = linetype,
             curvature = curvature, note = note)
}

edges <- bind_rows(
  # H2 -> H1: compartment attribution (Moderate, solid, project-generated) -- same row, straight
  edge_row("B_cell", "LTB", "solid", 0, "H2 primary"),
  edge_row("T_cell", "CXCL13", "solid", 0, "H2 primary"),
  edge_row("Myeloid", "CCL3", "solid", 0, "H2 primary"),
  edge_row("NK", "CCL4", "solid", 0, "H2 primary"),
  # H1 -> outcome (Moderate, solid, project-generated) -- curved to bow around intermediate rows
  edge_row("LTB", "Responder", "solid", 0.15, "H1"),
  edge_row("CXCL13", "Non_responder", "solid", -0.1, "H1"),
  edge_row("CCL3", "Non_responder", "solid", 0.05, "H1"),
  edge_row("CCL4", "Non_responder", "solid", 0.15, "H1"),
  # H4 -> outcome (Moderate, solid, project-generated)
  edge_row(modules$id[modules$group == "responder"], "Responder", "solid", -0.2, "H4"),
  edge_row(modules$id[modules$cluster_id == cl_metabolic], "Non_responder", "solid", 0.1, "H4"),
  edge_row(modules$id[modules$cluster_id == cl_e2f], "Non_responder", "solid", -0.15, "H4"),
  # Literature-derived (dashed, NOT generated by this project) -- short, direct
  edge_row("LTB", "lit_TLS", "dashed", 0, "literature concordance"),
  # bowed well clear of the Metabolic/NR and E2F module boxes sitting between the
  # lymphocyte-diff. module and this node (see lit_exhaustion's y placement above)
  edge_row(modules$id[modules$group == "responder"], "lit_exhaustion", "dashed", 0.6, "literature concordance"),
  edge_row("CCL3", "lit_wang", "dashed", -0.4, "H5c literature concordance")
)
straight_edges <- edges[edges$curvature == 0, ]
curved_edges   <- edges[edges$curvature != 0, ]

# ---- 9. H5 replication subtitles (short, factual tag; full nuance stays in caption/README) --

h5_tag_df <- data.frame(
  id = c(ligand_genes, "Module1_node", "Module2_node"),
  tag = c(h5a_tags, h5b_tags)
)
h5_tag_df$id[h5_tag_df$id == "Module1_node"] <- modules$id[modules$h5b_module %in% "Module1"]
h5_tag_df$id[h5_tag_df$id == "Module2_node"] <- modules$id[modules$h5b_module %in% "Module2"]
# shorten to the fixed 3-tier vocabulary for in-figure display; full qualifier text stays
# in the console record (section 11 below) and the README, never lost, just not crammed
# into the node box
short_tag <- function(x) {
  if (is.na(x)) return(NA_character_)
  if (grepl("Negative finding", x)) "H5: Negative finding"
  else if (grepl("Replicated", x)) "H5: Replicated"
  else "H5: Exploratory"
}
h5_tag_df$short <- vapply(h5_tag_df$tag, short_tag, character(1))

nodes <- nodes %>% left_join(h5_tag_df[, c("id", "short")], by = "id")
nodes$short[nodes$tier == "module" & is.na(nodes$short) & nodes$group == "responder"] <- "H5: not tested"
nodes$display_label <- ifelse(is.na(nodes$short), nodes$label, paste0(nodes$label, "\n[", nodes$short, "]"))

# ---- 10. Build the figure -------------------------------------------------------------------

fill_map <- c(
  responder = PROJECT_COLORS[["responder"]],
  non_responder = PROJECT_COLORS[["non_responder"]],
  neutral = "grey85"
)

# box half-extents sized to the ACTUAL number of lines in each node's display_label, so text
# never overflows its box regardless of tier (this was the root cause of the first draft's
# overlapping-text bug -- fixed sizes didn't account for variable label length)
n_lines <- vapply(strsplit(nodes$display_label, "\n"), length, integer(1))
nodes$hh <- pmax(0.35, 0.19 * n_lines + 0.12)
half_extent <- c(compartment = 0.5, ligand = 0.62, module = 0.85, outcome = 0.55, literature = 0.95)
nodes$hw <- half_extent[nodes$tier]

p <- ggplot() +
  geom_segment(
    data = straight_edges, aes(x = x, y = y, xend = xend, yend = yend, linetype = linetype),
    color = "grey40", linewidth = 0.5, arrow = arrow(length = unit(0.12, "cm"), type = "closed")
  ) +
  lapply(split(curved_edges, curved_edges$curvature), function(grp) {
    geom_curve(
      data = grp, aes(x = x, y = y, xend = xend, yend = yend, linetype = linetype),
      color = "grey40", linewidth = 0.5, arrow = arrow(length = unit(0.12, "cm"), type = "closed"),
      curvature = grp$curvature[1]
    )
  }) +
  geom_rect(
    data = nodes,
    aes(xmin = x - hw, xmax = x + hw, ymin = y - hh, ymax = y + hh,
        fill = group, linetype = border),
    color = "black", linewidth = 0.5
  ) +
  geom_text(
    data = nodes, aes(x = x, y = y, label = display_label),
    color = "black", size = 2.6, lineheight = 0.95
  ) +
  scale_fill_manual(
    values = fill_map,
    labels = c(responder = "Responder-elevated", non_responder = "Non-responder-elevated", neutral = "Attribution layer (not itself directional)"),
    name = "Node direction"
  ) +
  scale_linetype_manual(
    values = c(solid = "solid", dashed = "dashed"),
    labels = c(solid = "Generated within this project", dashed = "Literature-derived / externally unvalidated"),
    name = "Edge / node-border type",
    breaks = c("solid", "dashed")
  ) +
  guides(linetype = guide_legend(override.aes = list(fill = NA, color = "grey40"))) +
  coord_cartesian(xlim = c(-0.7, 6.3), ylim = c(-7.6, 11.4), clip = "off") +
  labs(
    title = "Figure 6. Evidence-driven systems synthesis (H1-H2-H4), with H5 replication status",
    subtitle = "Every node/edge is traceable to a completed, ledger-graded hypothesis module. Solid = this project's own findings (Moderate grade throughout);\ndashed = literature-derived or externally-unvalidated links. Bracketed subtitles report each node's independent-cohort replication tag (H5), computed\ndirectly from h5a/h5b's committed concordant_direction/significant columns -- not asserted narratively. Full per-cohort P-values in Fig. 5/README.",
    caption = paste0(
      "H0 (neutrophil recoverability) and H3 (omitted) are not part of this ligand/regulatory network and are not shown.\n",
      "H2-secondary, H4-secondary, and H4-communication (all Exploratory or Negative-finding) are deliberately not diagrammed to avoid\n",
      "overstating their confidence -- see 09_synthesis/README.md and the module READMEs for their full, unabridged treatment.\n",
      "CXCL8/CXCR1/CXCR2 do not appear in H1, H4, or H5c's committed tables and are therefore absent from this figure by construction,\n",
      "not by omission -- see 09_synthesis/README.md's section on the post-hoc CXCL8-CXCR1/2 check."
    )
  ) +
  theme_project_blank(base_size = 11) +
  theme(
    plot.caption = element_text(hjust = 0, size = rel(0.62), color = "grey40"),
    legend.position = "bottom",
    legend.box = "vertical"
  )

save_figure(p, "figures/figure6_synthesis_model", width = 12, height = 13, dpi = 300)

# ---- 11. Print a plain-text summary so the console transcript itself is a verifiable record --

cat("\n=== Figure 6 node summary (for cross-checking against the rendered image) ===\n")
print(nodes[, c("id", "tier", "group", "short")])
cat("\n=== Full (unshortened) H5 replication tags, for the record ===\n")
print(h5_tag_df)
cat("\n=== H4 module identities re-derived at r>0.7 (must match README's named modules) ===\n")
print(h4_modules[, c("module_label", "cluster_id", "group", "h5b_module")])
